name: Add Issues to Project

on:
  issues:
    types:
      # Issue の新規作成や変更、ラベル追加を契機にする（ラベル削除は別に考える必要あり）
      - opened
      - edited
      - labeled

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: testProject
          column: table1
          repo-token: ${{ secrets.PAT }}