name: Update Projects at Pull Request Review

on:
  pull_request_review:
    types: 
      - 'edited'
      - 'dismissed'
      - 'submitted'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
      - # Conditionally run the next step
        if: 'steps.reviews.outputs.approved >= 1 && steps.reviews.outputs.changes_requested == 0'
        run: |
          test=steps.reviews.outputs.approved
          echo $test