name: Update Projects at Pull Request Review

on:
  pull_request_review:
    types: 
      - 'edited'
      - 'dismissed'
      - 'submitted'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Review Count
        id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Use Count
        run: |
          test=${{steps.reviews.outputs.approved}}
          echo "approved:${{steps.reviews.outputs.approved}}"
          echo "requested:${{steps.reviews.outputs.changes_requested}}"
          echo "commented:${{steps.reviews.outputs.commented}}"
          echo "dismissed:${{steps.reviews.outputs.dismissed}}"